name: CI with Security

on:
    push:
        branches: [master, main]
    pull_request:
        branches: [master, main]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python 3.11
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -e .[dev]

            - name: Run tests
              run: |
                  pytest tests/ -v --tb=short

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -e .[dev]

            - name: Check formatting
              run: |
                  black --check --diff src/ tests/

            - name: Check imports
              run: |
                  isort --check-only --diff src/ tests/

            - name: Lint code
              run: |
                  ruff check src/ tests/

    build:
        runs-on: ubuntu-latest
        needs: [test, lint, security]
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install build dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install build twine

            - name: Build package
              run: python -m build

            - name: Check package
              run: twine check dist/*

    security:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python 3.11
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -e .[dev]
                  pip install bandit safety

            - name: Run security linting
              run: |
                  bandit -r src/ -f json -o bandit-report.json || true

            - name: Check for vulnerabilities
              run: |
                  safety check --output json || true
